export default {
  	ORC: 'ORC',
  	GOBLIN: 'GOBLIN',
  	CYCLOP: 'CYCLOP',
    ATTACK: 'ATTACK',
    WANDERING: 'WANDERING',
	SEARCH_BED: 'SEARCH_BED',
	SEARCH_FOOD: 'SEARCH_FOOD',
	FLEE: 'FLEE',
	RANGE_ATTACK: 'RANGE_ATTACK'
};
