export default {
    'ROOM': {
        'pillars' : {type: 'randomize', 'min':0, 'max':4},
        'beds': {type: 'randomize', 'min':1, 'max':2},
        'bookshelves': {type: 'randomize', 'min':1, 'max':2},
        'armorracks': {type: 'value', value:1},
        'weaponracks': {type: 'value', value:2},
        'torchs': {type: 'value', value:2},
        'crates': {type: 'value', value:3},
        'floortype': {type: 'value', value: "CONCRETE"},
        'walltype': {type: 'value', value: "CONCRETE"},
        'guards': {type: 'randomize', 'min':0, 'max':2},
        'traps': {type: 'randomize', 'min':0, 'max':1},
        'npcs': {type: 'pickone', value: ['DOCTOR', 'COMBAT_MASTER', 'LUTIN']},
        'treasure': {type: 'pickone', value: ['None', 'gold', 'armor']},
        'description': {type: 'value', value:'A very clean room with marble everywhere.'},
    },
    'TEMPLE': {
        'pillars' : {type: 'randomize', 'min':0, 'max':4},
        'beds': {type: 'randomize', 'min':1, 'max':2},
        'bookshelves': {type: 'randomize', 'min':1, 'max':2},
        'armorracks': {type: 'value', value:1},
        'weaponracks': {type: 'value', value:2},
        'torchs': {type: 'value', value:2},
        'crates': {type: 'value', value:3},
        'floortype': {type: 'value', value: "CONCRETE"},
        'walltype': {type: 'value', value: "CONCRETE"},
        'guards': {type: 'randomize', 'min':0, 'max':2},
        'traps': {type: 'randomize', 'min':0, 'max':1},
        'npcs': {type: 'pickone', value: ['DOCTOR', 'COMBAT_MASTER', 'LUTIN']},
        'treasure': {type: 'pickone', value: ['None', 'gold', 'armor']},
        'description': {type: 'value', value:'A very clean room with marble everywhere.'},
    },
    'CANTINA': {
        'pillars' : {type: 'randomize', 'min':0, 'max':4},
        'beds': {type: 'randomize', 'min':1, 'max':2},
        'bookshelves': {type: 'randomize', 'min':1, 'max':2},
        'armorracks': {type: 'value', value:1},
        'weaponracks': {type: 'value', value:2},
        'torchs': {type: 'value', value:2},
        'crates': {type: 'value', value:3},
        'floortype': {type: 'value', value: "CONCRETE"},
        'walltype': {type: 'value', value: "CONCRETE"},
        'guards': {type: 'randomize', 'min':0, 'max':2},
        'traps': {type: 'randomize', 'min':0, 'max':1},
        'npcs': {type: 'pickone', value: ['DOCTOR', 'COMBAT_MASTER', 'LUTIN']},
        'treasure': {type: 'pickone', value: ['None', 'gold', 'armor']},
        'description': {type: 'value', value:'A very clean room with marble everywhere.'},
    },
    'DORMITORY': {
        'pillars' : {type: 'randomize', 'min':0, 'max':4},
        'beds': {type: 'randomize', 'min':1, 'max':2},
        'bookshelves': {type: 'randomize', 'min':1, 'max':2},
        'armorracks': {type: 'value', value:1},
        'weaponracks': {type: 'value', value:2},
        'torchs': {type: 'value', value:2},
        'crates': {type: 'value', value:3},
        'floortype': {type: 'value', value: "CONCRETE"},
        'walltype': {type: 'value', value: "CONCRETE"},
        'guards': {type: 'randomize', 'min':0, 'max':2},
        'traps': {type: 'randomize', 'min':0, 'max':1},
        'npcs': {type: 'pickone', value: ['DOCTOR', 'COMBAT_MASTER', 'LUTIN']},
        'treasure': {type: 'pickone', value: ['None', 'gold', 'armor']},
        'description': {type: 'value', value:'A very clean room with marble everywhere.'},
    },
    'TREASURE_ROOM': {
        'pillars' : {type: 'randomize', 'min':0, 'max':4},
        'beds': {type: 'randomize', 'min':1, 'max':2},
        'bookshelves': {type: 'randomize', 'min':1, 'max':2},
        'armorracks': {type: 'value', value:1},
        'weaponracks': {type: 'value', value:2},
        'torchs': {type: 'value', value:2},
        'crates': {type: 'value', value:3},
        'floortype': {type: 'value', value: "CONCRETE"},
        'walltype': {type: 'value', value: "CONCRETE"},
        'guards': {type: 'randomize', 'min':0, 'max':2},
        'traps': {type: 'randomize', 'min':0, 'max':1},
        'npcs': {type: 'pickone', value: ['DOCTOR', 'COMBAT_MASTER', 'LUTIN']},
        'treasure': {type: 'pickone', value: ['None', 'gold', 'armor']},
        'description': {type: 'value', value:'A very clean room with marble everywhere.'},
    },
    'ARMORY': {
        'pillars' : {type: 'randomize', 'min':0, 'max':4},
        'beds': {type: 'randomize', 'min':1, 'max':2},
        'bookshelves': {type: 'randomize', 'min':1, 'max':2},
        'armorracks': {type: 'value', value:1},
        'weaponracks': {type: 'value', value:2},
        'torchs': {type: 'value', value:2},
        'crates': {type: 'value', value:3},
        'floortype': {type: 'value', value: "CONCRETE"},
        'walltype': {type: 'value', value: "CONCRETE"},
        'guards': {type: 'randomize', 'min':0, 'max':2},
        'traps': {type: 'randomize', 'min':0, 'max':1},
        'npcs': {type: 'pickone', value: ['DOCTOR', 'COMBAT_MASTER', 'LUTIN']},
        'treasure': {type: 'pickone', value: ['None', 'gold', 'armor']},
        'description': {type: 'value', value:'A very clean room with marble everywhere.'},
    },
    'FORGE': {
        'pillars' : {type: 'randomize', 'min':0, 'max':4},
        'beds': {type: 'randomize', 'min':1, 'max':2},
        'bookshelves': {type: 'randomize', 'min':1, 'max':2},
        'armorracks': {type: 'value', value:1},
        'weaponracks': {type: 'value', value:2},
        'torchs': {type: 'value', value:2},
        'crates': {type: 'value', value:3},
        'floortype': {type: 'value', value: "CONCRETE"},
        'walltype': {type: 'value', value: "CONCRETE"},
        'guards': {type: 'randomize', 'min':0, 'max':2},
        'traps': {type: 'randomize', 'min':0, 'max':1},
        'npcs': {type: 'pickone', value: ['DOCTOR', 'COMBAT_MASTER', 'LUTIN']},
        'treasure': {type: 'pickone', value: ['None', 'gold', 'armor']},
        'description': {type: 'value', value:'A very clean room with marble everywhere.'},
    }
};
